name: 2) Build and deploy to Scaleway

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - name: Bump version in package.json file
        run: |
          sed -i '0,/"version": "/{s/"version": "\([^#]*\)",/"version": "${{ github.ref_name }}",/}' package.json package-lock.json

      - uses: EndBug/add-and-commit@v9
        with:
          message: Bump version to ${{ github.ref_name }}
          push: origin HEAD:master

      - uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - run: npm install

      - run: npm run tsc

      - run: npm run lint

      - run: npm run prettier

